import * as fs from "fs";
import * as path from "path";

const compareImages = require("resemblejs/compareImages");
let counter = 1;

export interface ScenarioInformation {
  name: string;
  path: string;
  step: number;
  report: string;
}

// Helper function to ensure directories exist
function ensureDirSync(dirPath: string) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

// Helper function to save base64 data as an image
function saveBase64Image(base64Data: string, filePath: string) {
  const data = base64Data.replace(/^data:image\/\w+;base64,/, "");
  fs.writeFileSync(filePath, data, { encoding: "base64" });
}

// Helper function to compare images and generate a diff
async function compareAndGenerateDiff(
  oldImagePath: string,
  newImagePath: string,
  diffImagePath: string
): Promise<{ mismatchPercentage: string; diffBuffer: Buffer }> {
  try {
    const result = await compareImages(
      fs.readFileSync(oldImagePath),
      fs.readFileSync(newImagePath),
      {
        output: {
          errorColor: { red: 255, green: 0, blue: 255 },
          errorType: "movement",
          largeImageThreshold: 1200,
        },
        scaleToSameSize: true,
        ignore: "antialiasing",
      }
    );

    fs.writeFileSync(diffImagePath, result.getBuffer());
    return {
      mismatchPercentage: result.misMatchPercentage,
      diffBuffer: result.getBuffer(),
    };
  } catch (error) {
    console.error(`Error comparing images:`, error);
    throw error;
  }
}

// Helper function to generate HTML report
function generateHTMLReport(content: string): string {
  return `
    <html>
      <head>
        <title>Image Comparison Report</title>
        <style>
          body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f9;
            color: #333;
          }
          h1 {
            text-align: center;
            padding: 20px;
            background-color: #007bff;
            color: #fff;
            margin: 0;
            font-size: 2.5rem;
          }
          .container {
            max-width: 1200px;
            margin: 30px auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          }
          .section {
            margin-bottom: 40px;
          }
          .section h2 {
            font-size: 1.75rem;
            margin-bottom: 20px;
            color: #007bff;
          }
          .section .details {
            display: flex;
            justify-content: space-between;
            margin-top: 10px;
            font-size: 1.1rem;
          }
          .image-container {
            display: flex;
            justify-content: space-between;
            margin-bottom: 30px;
            gap: 20px;
          }
          .image-container div {
            width: 30%;
          }
          .image-container img {
            width: 100%;
            border: 2px solid #ddd;
            border-radius: 8px;
          }
          .details div {
            width: 30%;
          }
          .pass {
            color: green;
            font-weight: bold;
          }
          .fail {
            color: red;
            font-weight: bold;
          }
          .mismatch-percentage {
            font-size: 1.2rem;
          }
          hr {
            margin: 40px 0;
            border: 0;
            border-top: 1px solid #ccc;
          }
          .footer {
            text-align: center;
            font-size: 1rem;
            color: #777;
            margin-top: 30px;
          }
        </style>
      </head>
      <body>
        <h1>Image Comparison Report</h1>
        <div class="container">
          ${content}
        </div>
        <div class="footer">
          <p>Generated by Image Comparison Tool</p>
        </div>
      </body>
    </html>
  `;
}

// Main function to process image comparison
async function compareImagesWithResemblejs() {
  const screenshotsDir1 = "screenshots/kraken/4.5";
  const screenshotsDir2 = "screenshots/kraken/5.96.0";

  if (!fs.existsSync(screenshotsDir1) || !fs.existsSync(screenshotsDir2)) {
    console.error("One or both screenshot directories do not exist.");
    return;
  }

  const toProcessOld = fs.readFileSync(
    path.join(screenshotsDir1, "toProcess.json"),
    "utf8"
  );
  const toProcessNew = fs.readFileSync(
    path.join(screenshotsDir2, "toProcess.json"),
    "utf8"
  );

  const oldScenarios = JSON.parse(toProcessOld);
  const newScenarios = JSON.parse(toProcessNew);

  const vctReportDir = "vctReport";
  const outputImagesDir = path.join(vctReportDir, "outputImages");

  ensureDirSync(vctReportDir);
  ensureDirSync(outputImagesDir);

  let htmlContent = "";

  for (let i = 0; i < oldScenarios.length; i++) {
    const oldScenario: ScenarioInformation = oldScenarios[i];
    const newScenario: ScenarioInformation = newScenarios[i];

    if (oldScenario.name !== newScenario.name) {
      console.error("The scenarios do not match.");
      return;
    }

    const oldReport = fs.readFileSync(oldScenario.report, "utf8");
    const newReport = fs.readFileSync(newScenario.report, "utf8");

    const oldReportJSON = JSON.parse(oldReport);
    const newReportJSON = JSON.parse(newReport);

    const element = oldReportJSON[0].elements[0];
    const newElement = newReportJSON[0].elements[0];

    const id = element.id.replace(/ /g, "_");

    htmlContent += `
      <h1>Scenario ${counter++}: ${element.name}</h1>
      <hr>
    `;

    if (element?.steps) {
      for (let j = 0; j < element.steps.length; j++) {
        const oldSteps = element.steps[j];
        const newSteps = newElement.steps[j];

        if (oldSteps?.embeddings?.length) {
          const oldBase64Data = oldSteps.embeddings[0].data;
          const newBase64Data = newSteps.embeddings[0].data;

          const outputDirOld = path.join(outputImagesDir, "4.5", id);
          const outputDirNew = path.join(outputImagesDir, "5.96.0", id);
          const outputDirDiff = path.join(outputImagesDir, "diffs", id);

          ensureDirSync(outputDirOld);
          ensureDirSync(outputDirNew);
          ensureDirSync(outputDirDiff);

          const imageNameOld = `image_${j}_${Date.now()}.png`;
          const imageNameNew = `image_${j}_${Date.now()}.png`;
          const imageNameDiff = `diff_${j}_${Date.now()}.png`;

          const fullOldPath = path.join(outputDirOld, imageNameOld);
          const fullNewPath = path.join(outputDirNew, imageNameNew);
          const fullDiffPath = path.join(outputDirDiff, imageNameDiff);

          saveBase64Image(oldBase64Data, fullOldPath);
          saveBase64Image(newBase64Data, fullNewPath);

          // stepName
          const stepName = oldSteps.name;

          try {
            const { mismatchPercentage, diffBuffer } =
              await compareAndGenerateDiff(
                fullOldPath,
                fullNewPath,
                fullDiffPath
              );

            const resultClass =
              Number(mismatchPercentage) <= 20 ? "pass" : "fail";

            htmlContent += `
              <div class="section">
                <h2>Comparison for Step: ${stepName}</h2>
                <div class="image-container">
                  <div>
                    <h3>Old Image</h3>
                    <img src="${path.join(
              "outputImages",
              "4.5",
              id,
              imageNameOld
            )}" alt="Old Image"/>
                  </div>
                  <div>
                    <h3>New Image</h3>
                    <img src="${path.join(
              "outputImages",
              "5.96.0",
              id,
              imageNameNew
            )}" alt="New Image"/>
                  </div>
                  <div>
                    <h3>Diff Image</h3>
                    <img src="${path.join(
              "outputImages",
              "diffs",
              id,
              imageNameDiff
            )}" alt="Diff Image"/>
                  </div>
                </div>
                <div class="details">
                  <div><strong>Step:</strong> ${j}</div>
                  <div class="mismatch-percentage"><strong>Mismatch Percentage:</strong> ${mismatchPercentage}%</div>
                  <div><strong>Result:</strong> <span class="${resultClass}">${resultClass}</span></div>
                </div>
              </div>
              <hr>
            `;
          } catch (error) {
            console.error(`Error comparing images for ${id} step ${j}:`, error);
          }
        }
      }
    }
  }

  const finalHtml = generateHTMLReport(htmlContent);

  fs.writeFileSync(
    path.join(vctReportDir, "comparison_report.html"),
    finalHtml
  );
}

compareImagesWithResemblejs().catch(console.error);
